#pragma once

#define VIAL_KEYBOARD_UID {0x58, 0xDB, 0xD9, 0x24, 0x1B, 0x26, 0x66, 0x76}
// #define VIAL_UNLOCK_COMBO_ROWS { 1, 5 }
// #define VIAL_UNLOCK_COMBO_COLS { 10, 7 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 2
#define VIAL_KEY_OVERRIDE_ENTRIES 23
#define VIAL_TAP_DANCE_ENTRIES 6
#define VIAL_COMBO_ENTRIES 8

#undef MANUFACTURER
#define MANUFACTURER Unicomp

#undef PRODUCT
#define PRODUCT PC122 Converter
