#pragma once

#define VIAL_KEYBOARD_UID {0xF8, 0xE2, 0xB1, 0xC4, 0xF4, 0x17, 0x03, 0x86}

#define VIAL_UNLOCK_COMBO_ROWS { 1, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 4 }

#ifdef LOCKING_SUPPORT_ENABLE
    #undef LOCKING_SUPPORT_ENABLE
#endif

#ifdef LOCKING_RESYNC_ENABLE
    #undef LOCKING_RESYNC_ENABLE
#endif

#ifdef RGBLIGHT_ANIMATIONS
    #undef RGBLIGHT_ANIMATIONS
    #define RGBLIGHT_EFFECT_ALTERNATING
    #define RGBLIGHT_EFFECT_BREATHING
    #define RGBLIGHT_EFFECT_CHRISTMAS
    #define RGBLIGHT_EFFECT_KNIGHT
    #define RGBLIGHT_EFFECT_RAINBOW_MOOD
    #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
    #define RGBLIGHT_EFFECT_SNAKE
    #define RGBLIGHT_EFFECT_GRADIENT
#endif