#pragma once

#define VIAL_KEYBOARD_UID {0xF8, 0xE2, 0xB1, 0xC4, 0xF4, 0x17, 0x03, 0x86}

#define VIAL_UNLOCK_COMBO_ROWS { 1, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 4 }

#ifdef LOCKING_SUPPORT_ENABLE
    #undef LOCKING_SUPPORT_ENABLE
#endif

#ifdef LOCKING_RESYNC_ENABLE
    #undef LOCKING_RESYNC_ENABLE
#endif

#ifdef RGBLIGHT_ANIMATIONS
    #undef RGBLIGHT_ANIMATIONS
#endif

#ifdef RGB_MATRIX_ENABLE
    #define DRIVER_LED_TOTAL 16
    #define RGB_MATRIX_MAXIMUM_BRIGHTNESS 200
    #define RGB_DISABLE_WHEN_USB_SUSPENDED true
#endif
